import { Inter } from "next/font/google";
import "./globals.css";
import { LoadingProvider } from "@/context/loading-context";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-full">
        <div className="flex min-h-screen min-w-screen flex-col min-w-full bg-slate-100	!p-0 items-center grid justify-items-center">
          <LoadingProvider>{children}</LoadingProvider>
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
